import { Stack, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Table from "../components/Table";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Estarta Task</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Table />
      <Stack direction="column" alignItems="center" spacing={2}>
        <Typography variant="h4">Estarta Task - Amer Shboul</Typography>
        <Typography variant="subtitle1" color="red">
          ** the task asks the user to filter the content based on Employee Name
          that does not exist in the data comes from API, so i ignored the
          filter based on Employee Name
        </Typography>
        <Typography variant="subtitle1" color="red">
          ** you can click on each table head to sort it (decreasing,ascending)
        </Typography>
      </Stack>
    </div>
  );
};

export default Home;
